//! ALIEN: Artificial Life in Emergent Networks
//! GPU-accelerated ALife simulation engine compatible with Lenia and Conway.
const std = @import("std");

pub const AlienConfig = struct {
    seed: u64,
    width: u32,
    height: u32,
    dt: f32,
    growth_func: u32,
};

pub const wgsl_alien_step = comptimeWgslAlienStep();

fn comptimeWgslAlienStep() [:0]const u8 {
    return
        \\// ALIEN ALife Kernel — generated by zig-syrup/alien_alife.zig
        \\struct Params {
        \\    seed_lo: u32,
        \\    seed_hi: u32,
        \\    width: u32,
        \\    height: u32,
        \\    dt: f32,
        \\    growth_mode: u32,
        \\};
        \\@group(0) @binding(0) var<uniform> params: Params;
        \\@group(0) @binding(1) var<storage, read> input_grid: array<f32>;
        \\@group(0) @binding(2) var<storage, read_write> output_grid: array<f32>;
        \\@compute @workgroup_size(16, 16)
        \\fn main(@builtin(global_invocation_id) gid: vec3<u32>) {
        \\    let x = gid.x;
        \\    let y = gid.y;
        \\    if (x >= params.width || y >= params.height) { return; }
        \\    // Placeholder logic for simulation step
        \\    let idx = y * params.width + x;
        \\    output_grid[idx] = input_grid[idx];
        \\}
    ;
}

test "wgsl source generation" {
    const src = wgsl_alien_step;
    try std.testing.expect(src.len > 0);
    try std.testing.expect(std.mem.indexOf(u8, src, "fn main") != null);
}
